dist: xenial

services:
  - postgresql
matrix:
  include:
    - addons:
      postgresql: "9.4"
    - addons:
      postgresql: "9.6"

env:
- DJANGO=2.0 DB=postgres

before_script:
  - cp local_settings.travis.py local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
  - "3.8"

before_install:
  - cd decide

install:
  - pip install -r requirements.txt
script:
  - python ./manage.py test authentication
  - python ./manage.py test census
 
